/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.unbound.vista;

import com.mycompany.unbound.controlador.ControladorPrincipal;
import java.awt.event.ActionListener;

/**
 *
 * @author Admin
 */
public class GUIGuia extends javax.swing.JFrame {

    /**
     * Creates new form GUIGuia
     */
    public GUIGuia(ControladorPrincipal controlador) {
        initComponents();  
    }
public void escuchar(ActionListener controlador){
    btnQuitGuide.addActionListener(controlador);
    btnStory.addActionListener(controlador);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnQuitGuide = new javax.swing.JButton();
        btnStory = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnQuitGuide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/visual_btnQuit.png"))); // NOI18N
        btnQuitGuide.setActionCommand("quitguide");
        btnQuitGuide.setBorder(null);
        btnQuitGuide.setBorderPainted(false);
        btnQuitGuide.setContentAreaFilled(false);
        getContentPane().add(btnQuitGuide, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 680, -1, -1));

        btnStory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/visual_btnStory.png"))); // NOI18N
        btnStory.setActionCommand("showstory");
        btnStory.setBorder(null);
        btnStory.setBorderPainted(false);
        btnStory.setContentAreaFilled(false);
        getContentPane().add(btnStory, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 670, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/visual_guia.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnQuitGuide;
    private javax.swing.JButton btnStory;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
