/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.unbound.vista;

import com.mycompany.unbound.controlador.ControladorPrincipal;
import javax.swing.JFrame;

/**
 *
 * @author Krogner
 */
public final class GUIInGameMenu extends JFrame {

    /**
     * Creates new form GUIInGameMenu
     * @param controlador
     */
    public GUIInGameMenu(ControladorPrincipal controlador) {
        initComponents();
        escuchar(controlador);
    }

    private GUIInGameMenu() {
      
    }


    public void escuchar(ControladorPrincipal controlador) {
        btnQuitGame.addActionListener(controlador);
        btnResume.addActionListener(controlador);
        btnScore.addActionListener(controlador);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnScore = new javax.swing.JButton();
        btnResume = new javax.swing.JButton();
        btnQuitGame = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnScore.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/visual_btnScore.png"))); // NOI18N
        btnScore.setActionCommand("showScore");
        btnScore.setBorder(null);
        btnScore.setBorderPainted(false);
        btnScore.setContentAreaFilled(false);
        btnScore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnScoreActionPerformed(evt);
            }
        });
        getContentPane().add(btnScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, -1, -1));

        btnResume.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/visual_btnResume.png"))); // NOI18N
        btnResume.setActionCommand("resumeGame");
        btnResume.setBorder(null);
        btnResume.setBorderPainted(false);
        btnResume.setContentAreaFilled(false);
        getContentPane().add(btnResume, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        btnQuitGame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/visual_btnQuitEspacioMenu.png"))); // NOI18N
        btnQuitGame.setActionCommand("endGame");
        btnQuitGame.setBorder(null);
        btnQuitGame.setBorderPainted(false);
        btnQuitGame.setContentAreaFilled(false);
        getContentPane().add(btnQuitGame, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, -1));

        jLabel1.setBackground(new java.awt.Color(82, 62, 81));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/visual_espacio.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnScoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnScoreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnScoreActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnQuitGame;
    private javax.swing.JButton btnResume;
    private javax.swing.JButton btnScore;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
