/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.unbound.vista;

import com.mycompany.unbound.controlador.ControladorPrincipal;

/**
 *
 * @author Admin
 */
public class GUIPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form GUIPrincipal
     */
    public GUIPrincipal(ControladorPrincipal controlador) {
        initComponents();
        escuchar(controlador);
    }

    public void escuchar(ControladorPrincipal controlador) {
        btnPlay.addActionListener(controlador);
        btnGuide.addActionListener(controlador);
        btnQuit.addActionListener(controlador);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPlay = new javax.swing.JButton();
        btnGuide = new javax.swing.JButton();
        btnQuit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/visual_btnPlay.png"))); // NOI18N
        btnPlay.setActionCommand("play");
        btnPlay.setBorder(null);
        btnPlay.setBorderPainted(false);
        btnPlay.setContentAreaFilled(false);
        getContentPane().add(btnPlay, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, -1, -1));

        btnGuide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/visual_btnGuide.png"))); // NOI18N
        btnGuide.setActionCommand("guide");
        btnGuide.setBorder(null);
        btnGuide.setBorderPainted(false);
        btnGuide.setContentAreaFilled(false);
        getContentPane().add(btnGuide, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, -1, -1));

        btnQuit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/visual_btnQuit.png"))); // NOI18N
        btnQuit.setActionCommand("quit");
        btnQuit.setBorder(null);
        btnQuit.setBorderPainted(false);
        btnQuit.setContentAreaFilled(false);
        getContentPane().add(btnQuit, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 490, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/visual_principal.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuide;
    private javax.swing.JButton btnPlay;
    private javax.swing.JButton btnQuit;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
