/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.unbound.vista;

import com.mycompany.unbound.controlador.ControladorPrincipal;

/**
 *
 * @author Krogner
 */
public class GUIScore extends javax.swing.JFrame {

    /**
     * Creates new form GUIScore
     */
    public GUIScore(ControladorPrincipal controlador) {
        initComponents();
        escuchar(controlador);
    }

    public GUIScore() {
      
    }
     public void escuchar (ControladorPrincipal controlador){
        btnBackInGameMenu.addActionListener(controlador);
     } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBackInGameMenu = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBackInGameMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/visual_btnBack.png"))); // NOI18N
        btnBackInGameMenu.setActionCommand("goBackMenu");
        btnBackInGameMenu.setBorder(null);
        btnBackInGameMenu.setBorderPainted(false);
        btnBackInGameMenu.setContentAreaFilled(false);
        getContentPane().add(btnBackInGameMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/visual_espacio.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackInGameMenu;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
