/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.unbound.vista;

import com.mycompany.unbound.controlador.ControladorPrincipal;
import com.mycompany.unbound.modelo.AreaJuego;
import com.mycompany.unbound.modelo.Personaje;
import java.awt.Graphics;
import java.awt.event.KeyListener;
import javax.swing.ImageIcon;

/**
 *
 * @author Admin
 */
public class PanelLaberinto extends javax.swing.JPanel {

    private AreaJuego areaJuego;
    private ImageIcon fondo;
    private ControladorPrincipal controlador;
    private Personaje personaje;

    /**
     * Creates new form PanelLaberinto
     */
    public PanelLaberinto() {
        initComponents();
        fondo = new ImageIcon("src/main/resources/img/LABERYNTH-22.jpg");
        areaJuego = new AreaJuego();
        personaje = new Personaje(597, 393, new ImageIcon("./src/main/resources/img/abajo.gif"));

    }

    public void escuchar(ControladorPrincipal controlador) {
        this.controlador = controlador;
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);

        // LABRINTO
        if (fondo != null) {
            fondo.paintIcon(this, g, 0, 0);
        }

        // areaJuego
//        if (areaJuego != null) {
//            areaJuego.paintComponent(g);
//        }
//        
        //personaje
        g.drawImage(personaje.getImageIcon().getImage(), personaje.getX(), personaje.getY(), null);
        // personaje.show(g);
    }

    // Actualizar el estado del juego
    public void actualizarEstado(String direccionA) {
        System.out.println(direccionA);
        switch (direccionA) {
            case "arriba":
                personaje.moverArriba();
                break;
            case "abajo":
                personaje.moverAbajo();
                break;
            case "izquierda":
                personaje.moverIzquierda();
                break;
            case "derecha":
                personaje.moverDerecha();
                break;
            default:

                break;

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 858, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 695, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
