/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.unbound.vista;

/**
 *
 * @author Admin
 */
public class PanelTiempoPuntos extends javax.swing.JPanel {

    /**
     * Creates new form PanelTiempoVidasPuntos
     */
    public PanelTiempoPuntos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gTiempo = new javax.swing.JLabel();
        gPuntos = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gTiempo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/visual_tiempo.png"))); // NOI18N
        add(gTiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        gPuntos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/visual_queso.png"))); // NOI18N
        add(gPuntos, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel gPuntos;
    private javax.swing.JLabel gTiempo;
    // End of variables declaration//GEN-END:variables
}
